export const actionTypes = {
    USER_SIGN_IN: "USER_SIGN_IN",
    USER_SIGN_OUT: "USER_SIGN_OUT",
    FETCH_LATEST_POSTS: "FETCH_LATEST_POSTS",
    CREATE_NEW_POST: "CREATE_NEW_POST",
    FETCH_POST_BY_ID: "FETCH_POST_BY_ID",
    FETCH_ALL_CATEGORIES: "FETCH_ALL_CATEGORIES",
};
